name: Build Pipeline

on: [push, pull_request, workflow_dispatch]

jobs:
  Palladio-ReverseEngineering-SoMoX-JaMoPP:
    uses: PalladioSimulator/Palladio-Build-ActionsPipeline/.github/workflows/build.yml@master
    with:
      use-display-output: true
      no-caching: true
      runner-label: ubuntu-latest
      deploy-updatesite: 'target/classes/p2/final'
    secrets:
      SERVER_SSH_KEY: ${{ secrets.DEPLOYMENT_SERVER_SSH_KEY }}
      REMOTE_HOST: ${{ secrets.DEPLOYMENT_REMOTE_HOST }}
      REMOTE_PORT: ${{ secrets.DEPLOYMENT_REMOTE_PORT }}
      REMOTE_USER: ${{ secrets.DEPLOYMENT_REMOTE_USER }}
      REMOTE_TARGET: ${{ secrets.DEPLOYMENT_REMOTE_TARGET }}
