name: Build Pipeline

on: [push, pull_request, workflow_dispatch]

jobs:
  Palladio-Build-UpdateSite:
    uses: MDSD-Tools/Maven-Tycho-Action/.github/workflows/build.yml@main
    with:
      use-display-output: true
      no-caching: true
      deploy-updatesite: "target/classes/p2/final"
    secrets:
      SERVER_SSH_KEY: ${{ secrets.DEPLOYMENT_SERVER_SSH_KEY }}
      REMOTE_HOST: ${{ secrets.DEPLOYMENT_REMOTE_HOST }}
      REMOTE_PORT: ${{ secrets.DEPLOYMENT_REMOTE_PORT }}
      REMOTE_USER: ${{ secrets.DEPLOYMENT_REMOTE_USER }}
      REMOTE_TARGET: ${{ secrets.DEPLOYMENT_REMOTE_TARGET }}
