# This workflow enables continuous quality assurance
name: Continual Improvement Process

on:
  push:
  pull_request:
  schedule:
    - cron: '4 2 * * 0' # once a week, Sundays at 02:04 UTC.
  workflow_dispatch:

jobs:
  verify:
    name: Continual Improvement Process
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set Up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Run Maven
      run: mvn -B -U clean verify
    - name: Set Up Snyk CLI
      uses: snyk/actions/setup@master
    - name: Run Snyk Code Test
      run: snyk code test --sarif > snyk-code.sarif
    - name: Snyk Open Source Monitor
      run: snyk monitor --all-projects
    - name: Upload Code Scanning Results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk-code.sarif
